### PR TITLE
HTML and CSS code for the NYT article 

### PR DESCRIPTION
**Pull request by widzthedvloper**
In this pull request we made the changes asked by the TSE
we finished the entire page

### CODE REVIEW

**Comment by widzthedvloper** [comment]
Please leave us a comment about the type of error we our getting from the linter.

**Comment by mimipeshy** [comment]
### STATUS :CHANGES REQUIRED :red_circle:  :recycle: 

Hey team @widzthedvloper  and @ixboy , good job on working on the previous comments left by the previous TSE :muscle: , however before approving it, lets work on a few things

- [ ] Do not close a PR after you have worked on any feedback given by the TSEs, when filling in the request for review form just give the current PR. It helps track the feedback you are being given.

- [ ] Some sections of the README file are missing such as:
1. The screenshot link is broken, fix that

2. The live demo link is not working. In this case, you can deploy your page using [ghpages](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site) or netflify whichever you find to be easy to work with.
3. Add a section called getting started. In this section, give steps that people need to take to use your website locally.
- You can use this template to help with the [README](https://github.com/microverseinc/readme-template)

- [ ]  Your social media icons are stretched out, kindly work on an appropriate height for the icons.

**Original**
IC 
**Clone**
so

- [ ] Reduce the margin space between each paragraph.

- [ ] You are missing the editors picks aside section as shown below :arrow_down: 

s1

- [ ] The section `More in space and astronomy` is missing on your page. KIndly add it and also take note of the styling from the original page.
sp

- [ ] Add more styling to the footer section to make it look like the original one.
**Original** 
ft

**Clone**
ft1

Thats all :smile: , kindly submit another review when done.

Happy Coding :computer:  

Regards
Peris Ndanu
Feel free to slack me if you have any questions

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @ixboy and @widzthedvloper, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR. Most of the requirements already accomplished👌. 👏👏  I appreciate your hard work in replicating nytimes.com.   Kindly fix the following issues.

[REQUIRED]

- [ ] Fix the web hint errors.
- [ ] Fix the suggested newsletter section style. Give some spacing and implement the add(+) button.

| Your Copy | Source  | 
| :---:         |     :---:      | 
|Screen Shot 2020-11-28 at 2 53 21 AM|Screen Shot 2020-11-28 at 2 46 11 AM|

- [ ] Fix the bottom navigations and footer fonts

| Your Copy | Source  | 
| :---:         |     :---:      | 
|Screen Shot 2020-11-28 at 2 47 07 AM|Screen Shot 2020-11-28 at 2 48 20 AM|

- [ ] Don't repeat CSS rules create common utility classes for common CSS rules. 
Example: 
```
.flex {
display: flex;
}
```

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: :stop_sign: 
Hello team! I've checked your site and it looks amazing. :muscle: However, there are some minor issues that need to be solved before moving on.

- [ ] In between more in space and the most popular parts there is a gap. You can decrease this gap by making the images bigger. Kindly implement this.
sc

- [ ] Your NerYork Times logo is broken. Kindly fix this.
sc2

Please fix those issues and submit for a re-review.
If you have any questions about the review, feel free to reach me via Slack. :100: 
Eyüp Sercan UYGUR

**Review by Srjnnnn — APPROVED** [review]
## Status: Approved :partying_face: :tada: 
Hello, team again! Thanks for making the requested changes. Your page looks amazing. :muscle: 

You can merge it, and move on to the next project. :100: 
Eyüp Sercan UYGUR

**Comment by ixboy** [comment]
> ## Status: Approved partying_face tada
> 
> Hello, team again! Thanks for making the requested changes. Your page looks amazing. muscle
> 
> You can merge it, and move on to the next project. 100
> Eyüp Sercan UYGUR

Thank You very Much :)

**Pull request merged**
